export const USER_LOGOUT = 'USER_LOGOUT'

export const AuthConstants = {
    LOGIN: 'AUTH_LOGIN',
    LOGOUT: 'AUTH_LOGOUT',
    FAILED: 'AUTH_FAILED',
    AUTH: 'CHECK_USER_AUTH',
    UPDATE: 'UPDATE_PROFILE',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED'
}

export const RoleConstants = {
    GET: 'GET_ROLES',
    UPDATE: 'UPDATE_ROLE',
    FAILED: 'FAILED_ROLE',
    DELETE: 'ROLE_DELETE',
    ADD: 'ROLE_ADD'
}

export const UserConstants = {
    GET: 'GET_USERS',
    UPDATE: 'USERS_UPDATE',
    FAILED: 'USERS_FAILED',
    DELETE: 'USER_DELETE',
    ADD: 'USERS_ADD'
}
export const SubjectConstants = {
    GET: 'GET_SUBJECTS',
    UPDATE: 'SUBJECTS_UPDATE',
    FAILED: 'SUBJECTS_FAILED',
    DELETE: 'SUBJECTS_DELETE',
    ADD: 'SUBJECTS_ADD',
    GET_CLASSES: 'GET_ALL_CLASSES',
    ADD_CLASS: 'ADD_NEW_CLASS',
    UPDATE_CLASS: 'UPDATE_CLASS',
    DELETE_CLASS: 'DELETE_CLASS',
    CLEAR_SUBJECTS: 'CLEAR_SUBJECTS',
    SUBJECT_DETAILS: 'GET_SUBJECT_DETAILS',
    CLEAR_SUBJECT: "CLEAR_SUBJECT_DETAILS",
    ADD_CHAPTER:'ADD_CHAPTER',
    DELETE_CHAPTER:'DELETE_CHAPTER',
    UPDATE_CHAPTER:'UPDATE_CHAPTER',
    FAILED_CHAPTER:'CHAPTER_FAILED',
    ADD_TOPIC:'ADD_TOPIC',
    UPDATE_TOPIC:'UPDATE_TOPIC',
    FAILED_TOPIC:'FAILED_TOPIC',
    DELETE_TOPIC:'DELETE_TOPIC',
    ADD_CONTENT:'ADD_CONTENT',
    UPDATE_CONTENT:'UPDATE_CONTENT',
    FAILED_CONTENT:'FAILED_CONTENT',
    DELETE_CONTENT:'DELETE_CONTENT',
}
export const ClassesConstants = {
    GET: 'GET_CLASSES',
    UPDATE: 'CLASSES_UPDATE',
    FAILED: 'CLASSES_FAILED',
    DELETE: 'CLASSES_DELETE',
    ADD: 'CLASSES_ADD'
}
export const ContentsConstants = {
    GET: 'GET_CONTENTS',
    UPDATE: 'CONTENTS_UPDATE',
    FAILED: 'CONTENTS_FAILED',
    DELETE: 'CONTENTS_DELETE',
    ADD: 'CONTENTS_ADD'
}
export const QuestionBankConstants = {
    GET: 'GET_QUESTIONBANK',
    GETBYTAGS:'GETBYTAGS_QUESTIONBANK',
    UPDATE: 'QUESTIONBANK_UPDATE',
    FAILED: 'QUESTIONBANK_FAILED',
    DELETE: 'QUESTIONBANK_DELETE',
    ADD: 'QUESTIONBANK_ADD',
    CLEAR:'CLEAR_GETBYTAGS'
}
export const GalleryConstants = {
    GET: 'GET_GALLERY',
    UPDATE: 'GALLERY_UPDATE',
    FAILED: 'GALLERY_FAILED',
    DELETE: 'GALLERY_DELETE',
    ADD: 'GALLERY_ADD',
    ADDGALLERYIMAGE:'ADD_GALLERY_IMAGES',
}
export const NewsConstants = {
    GET: 'GET_NEWS',
    UPDATE: 'NEWS_UPDATE',
    FAILED: 'NEWS_FAILED',
    DELETE: 'NEWS_DELETE',
    ADD: 'NEWS_ADD',
}
export const HeadlineConstants = {
    GET: 'GET_HEADLINES',
    UPDATE: 'HEADLINE_UPDATE',
    FAILED: 'HEADLINE_FAILED',
    DELETE: 'HEADLINE_DELETE',
    ADD: 'HEADLINE_ADD',
}
export const TendersConstants = {
    GET: 'GET_TENDERS',
    UPDATE: 'TENDERS_UPDATE',
    FAILED: 'TENDERS_FAILED',
    DELETE: 'TENDERS_DELETE',
    ADD: 'TENDERS_ADD',
}
export const JobsConstants = {
    GET: 'GET_JOBS',
    UPDATE: 'JOBS_UPDATE',
    FAILED: 'JOBS_FAILED',
    DELETE: 'JOBS_DELETE',
    ADD: 'JOBS_ADD',
}
export const DownloadsConstants = {
    GET: 'GET_DOWNLOADS',
    UPDATE: 'DOWNLOADS_UPDATE',
    FAILED: 'DOWNLOADS_FAILED',
    DELETE: 'DOWNLOADS_DELETE',
    ADD: 'DOWNLOADS_ADD',
}
export const LinksConstants = {
    GET: 'GET_LINKS',
    UPDATE: 'LINKS_UPDATE',
    FAILED: 'LINKS_FAILED',
    DELETE: 'LINKS_DELETE',
    ADD: 'LINKS_ADD',
}
export const SliderConstants = {
    GET: 'GET_SLIDER',
    UPDATE: 'SLIDE_UPDATE',
    FAILED: 'SLIDE_FAILED',
    DELETE: 'SLIDE_DELETE',
    ADD: 'SLIDE_ADD',
}
export const VideosConstants = {
    GET: 'GET_VIDEOS',
    UPDATE: 'VIDEO_UPDATE',
    FAILED: 'VIDEOS_FAILED',
    DELETE: 'VIDEO_DELETE',
    ADD: 'VIDEO_ADD',
}
export const LocationsConstants = {
    GET: 'GET_LOCATIONS',
    UPDATE: 'LOCATION_UPDATE',
    FAILED: 'LOCATIONS_FAILED',
    DELETE: 'LOCATION_DELETE',
    ADD: 'LOCATION_ADD',
}
export const TeamConstants = {
    GET: 'GET_TEAM',
    UPDATE: 'TEAM_UPDATE',
    FAILED: 'TEAM_FAILED',
    DELETE: 'TEAM_DELETE',
    ADD: 'TEAM_ADD',
}
export const SocialLinksConstants = {
    GET: 'GET_SOCIALLINKS',
    UPDATE: 'SOCIALLINK_UPDATE',
    FAILED: 'SOCIALLINKS_FAILED',
    DELETE: 'SOCIALLINK_DELETE',
    ADD: 'SOCIALLINK_ADD',
}
export const ComponentsConstants = {
    GET: 'GET_COMPONENTS',
    UPDATE: 'COMPONENT_UPDATE',
    FAILED: 'COMPONENTS_FAILED',
    DELETE: 'COMPONENT_DELETE',
    ADD: 'COMPONENT_ADD',
}